### ISSUE TITLE
JSON Crash

### ISSUE THREAD

**Issue by SPDEX** [klein-thibault/StarcraftWatch#2]
Need to fix VideosViewController.swift:

```
    Alamofire.request(.GET, self.videosURL, parameters: nil)
        .responseJSON { (result) -> Void in
            let JSON: NSDictionary = result.result.value as! NSDictionary
            let items = JSON["items"] as! NSArray
            for item in items {
                let youtubeSearchItem = YouTubeSearchResult(jsonDict: item as! NSDictionary)
                self.videos.append(youtubeSearchItem)
            }
            self.videosCollectionView.reloadData()
    }
```

**Comment by nazimamin** [comment]
Change to something like this: 
        Alamofire.request(.GET, self.videosURL, parameters: nil)
            .responseJSON { result in
                let JSON: NSDictionary = result.result.value as! NSDictionary
                let items = JSON["items"] as! NSDictionary
                for (_, item) in items {
                    let youtubeSearchItem = YouTubeSearchResult(jsonDict: item["id"] as! NSDictionary)
                    self.videos.append(youtubeSearchItem)
                }
                self.videosCollectionView.reloadData()
        }

**Comment by ThibaultKlein** [comment]
Fixed, thanks for the issue.
